# Generated by Django 4.2.10 on 2024-05-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_ct', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=20)),
                ('review', models.CharField(max_length=255)),
            ],
        ),
    ]
