# Generated by Django 4.2.10 on 2024-05-27 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='review_ct',
        ),
    ]
