# Generated by Django 4.2.10 on 2024-05-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_webcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='rating',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
