# Generated by Django 4.2.10 on 2024-05-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_reviews_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
