# Generated by Django 4.2.10 on 2024-05-28 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_reviews_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='rating',
            new_name='cus_rating',
        ),
    ]
