# Generated by Django 4.2.10 on 2024-05-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_rename_rating_reviews_cus_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='cus_rating',
            field=models.ImageField(blank=True, default=0, null=True, upload_to=''),
        ),
    ]
