# Generated by Django 4.2.10 on 2024-05-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_reviews_cus_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
