# Generated by Django 4.2.10 on 2024-05-28 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='cus_rating',
        ),
    ]
