# Generated by Django 4.2.10 on 2024-05-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_delete_reviews'),
    ]

    operations = [
    ]
