# Generated by Django 4.2.10 on 2024-05-30 04:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='review_image'),
        ),
    ]
