# Generated by Django 4.2.10 on 2024-05-30 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_reviews_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='galery',
            name='main_p',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
