# Generated by Django 4.2.10 on 2024-05-30 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_galery_main_p'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galery',
            name='main_p',
        ),
    ]
