# Generated by Django 4.2.10 on 2024-05-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_remove_galery_main_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='galery',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
