# Generated by Django 4.2.10 on 2024-05-31 08:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_galery_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galery',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
