# Generated by Django 4.2.10 on 2024-06-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_rename_sudo_admin_user_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='galery',
            name='iframe',
            field=models.CharField(blank=True, null=True),
        ),
    ]
