# Generated by Django 4.2.10 on 2024-06-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_galery_iframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcontent',
            name='iframe',
            field=models.CharField(blank=True, null=True),
        ),
    ]
